### ISSUE TITLE
typo

### ISSUE THREAD

**Issue by jmhar3** [learn-co-curriculum/fewpjs-getter-and-setter-methods#14]
typo in last line of introduction. "illustrate these *these* concepts."

**Comment by ihollander** [comment]
Thanks for flagging @jmhar3 - this typo was fixed on GitHub by this earlier PR: https://github.com/learn-co-curriculum/fewpjs-getter-and-setter-methods/pull/6

The changes might not be reflected in Canvas depending on when your course started.
