### ISSUE TITLE
Dumb

### ISSUE THREAD

**Issue by jesspesale** [learn-co-curriculum/fewpjs-getter-and-setter-methods#17]
Thanks for raising this issue! Future learners thank you for your diligence. In
order to help the curriculum team address the problem, please use this template
to submit your feedback. We'll work on addressing the issue as soon as we can.

Please fill out as much of the information below as you can (it's ok if you
don't fill out every section). The more context we have, the easier it will be
to fix your issue!

_**Note**: you should only raise issues related to the contents of this lesson.
If you have questions about your code or need help troubleshooting, reach out to
an instructor/your peers._

---

## Link to Canvas

> Add a link to the assignment in Canvas here.
https://learning.flatironschool.com/courses/1882/assignments/125595?module_item_id=259562
## What should be changed?

> Suggest your change here. Let us know what section or line of the Readme needs
> to be updated, and any proposed corrections. Include the line number(s) if
> possible.

I think this lab/lesson is written really poorly and makes absolutely no sense. If you read the lesson and look at the example of getters and setters it does not explain at all what you are supposed to do for a getter and setter. You think a "set diameter" function would set the value of the diameter, yet your are doing the complete opposite? Using the diameter to se a radius with the set diameter function just seems very dumb to me. I was a math major and understand that a radius is half of the diameter, but I do not understand why you would be calculating the radius in a diameter setter method. It truly makes no sense to me and talking to a TC for 30 minutes and still not understanding why you have to do that was just very frustrating. I would use better examples if you are going to do a lab like this.

## Additional context

> Add any other context about the problem here.

**Comment by lizbur10** [comment]
Hi there! Thank you for posting this issue! I have expanded the instructions to clarify the requirements. Please note that the change will probably not be reflecting in your Canvas lesson page but it will be in place for students moving forward.

Thanks for contributing to the Flatiron School curriculum! 💙
