### ISSUE TITLE
Typo in last sentence in Introduction paragraph

### ISSUE THREAD

**Issue by sjwakeman** [learn-co-curriculum/fewpjs-getter-and-setter-methods#7]
There are two these in the sentence:

In this lab, we will be building pseudo-properties to illustrate these these concepts.

**Comment by Sdcrouse** [comment]
I can see one typo (`these these`), but what's the other one?

**Comment by Dbhmunro** [comment]
The other typo that I see is in this phrase "we can return calculated or dynamic data based an object properties". The "an" should be "on".

**Comment by Sdcrouse** [comment]
OK. I fixed that in a pull request. Also, it appears that I misread what sjwakeman said. I thought he meant "two *of* these" (i.e. two typos), but he really meant that there are two "these" in a sentence.
